namespace CMS.API.Models;

/// <summary>
/// Response model for dbo.PublishStatus (上架狀態) — a fixed enum-like table.
/// <see cref="Pkid"/> is the primary key, but a <b>tinyint that is NOT an IDENTITY</b>: the value is
/// supplied by the client on create, not generated by the database. It is the FK target of
/// Course.PublishStatus_pkid.
/// </summary>
public class PublishStatus
{
    public byte Pkid { get; set; }
    public string Description { get; set; } = string.Empty;
    public bool IsDraft { get; set; }
    public bool IsPublished { get; set; }
    public bool IsDiscontinued { get; set; }

    /// <summary>對應課程數 — subquery count over Course.PublishStatus_pkid. Display only.</summary>
    public int CourseCount { get; set; }
}
